config/routes.rb
Rails.application.routes.draw do
  # GET '/tasks': get all your tasks.
  get 'tasks', to: 'tasks#index'
   # GET '/tasks/new': get the form to create a new task
  get 'tasks/new', to: 'tasks#new'
  # GET '/tasks/:id': get a precise task, e.g GET '/tasks/3' fetches the task with id=3
  get 'tasks/:id', to: 'tasks#show', as: 'task'
   # POST '/tasks': post a new task
  post 'tasks', to: 'tasks#create'
  # GET '/tasks/:id/edit': get the form to edit an existing task
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'task/edit'
  # PATCH '/tasks/:id': update an existing task
  patch 'tasks/:id', to: 'tasks#update'
  # DELETE '/tasks/:id': delete an existing task
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :deadline)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/create.html.erb
<h1>Tasks#create</h1>
<p>Find me in app/views/tasks/create.html.erb</p>

app/views/tasks/delete.html.erb
<h1>Tasks#delete</h1>
<p>Find me in app/views/tasks/delete.html.erb</p>

app/views/tasks/edit.html.erb
<h1>Which task would you like to change/update?</h1>
<%= form_for(@task) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :description %>
<%= f.text_field :description %>

<%= f.label :deadline %>
<%= f.text_field :deadline %>

<%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>This is your To Do List</h1>

<%= link_to "New Task", tasks_new_path%>


<%@tasks.each do |task| %>
<h2><%= link_to task.name, task_path(task) %></h2>
<p><%= task.description %></p>
<p><%= task.deadline %></p>
<%= link_to "Delete", task_path(task),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
<%= link_to "Edit task", task_edit_path(task) %>
<% end %>

app/views/tasks/new.html.erb
<h1>Which task would you like to add?</h1>
<%= form_for(@task) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :description %>
<%= f.text_field :description %>

<%= f.label :deadline %>
<%= f.text_field :deadline %>

<%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h2><%= @task.name %></h2>
<p><%= @task.description %></p>
<p><%= @task.deadline %></p>

<%= link_to "Back to todo list", tasks_path %>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>